# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jan  9 20:28:45 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(668, 454)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layout_roomba_info = QtGui.QHBoxLayout()
        self.layout_roomba_info.setObjectName(_fromUtf8("layout_roomba_info"))
        self.label_roomba_at = QtGui.QLabel(self.centralWidget)
        self.label_roomba_at.setObjectName(_fromUtf8("label_roomba_at"))
        self.layout_roomba_info.addWidget(self.label_roomba_at)
        self.text_roomba_ip = QtGui.QLineEdit(self.centralWidget)
        self.text_roomba_ip.setObjectName(_fromUtf8("text_roomba_ip"))
        self.layout_roomba_info.addWidget(self.text_roomba_ip)
        self.label_roomba_on = QtGui.QLabel(self.centralWidget)
        self.label_roomba_on.setObjectName(_fromUtf8("label_roomba_on"))
        self.layout_roomba_info.addWidget(self.label_roomba_on)
        self.text_roomba_port = QtGui.QLineEdit(self.centralWidget)
        self.text_roomba_port.setObjectName(_fromUtf8("text_roomba_port"))
        self.layout_roomba_info.addWidget(self.text_roomba_port)
        self.verticalLayout.addLayout(self.layout_roomba_info)
        self.layout_controls = QtGui.QHBoxLayout()
        self.layout_controls.setObjectName(_fromUtf8("layout_controls"))
        self.groupbox_commands = QtGui.QGroupBox(self.centralWidget)
        self.groupbox_commands.setObjectName(_fromUtf8("groupbox_commands"))
        self.gridLayout = QtGui.QGridLayout(self.groupbox_commands)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_reset = QtGui.QPushButton(self.groupbox_commands)
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.gridLayout.addWidget(self.btn_reset, 0, 0, 1, 1)
        self.btn_test = QtGui.QPushButton(self.groupbox_commands)
        self.btn_test.setObjectName(_fromUtf8("btn_test"))
        self.gridLayout.addWidget(self.btn_test, 0, 1, 1, 1)
        self.btn_power_off = QtGui.QPushButton(self.groupbox_commands)
        self.btn_power_off.setObjectName(_fromUtf8("btn_power_off"))
        self.gridLayout.addWidget(self.btn_power_off, 1, 0, 1, 1)
        self.btn_wake_up = QtGui.QPushButton(self.groupbox_commands)
        self.btn_wake_up.setObjectName(_fromUtf8("btn_wake_up"))
        self.gridLayout.addWidget(self.btn_wake_up, 1, 1, 1, 1)
        self.btn_beep_lo = QtGui.QPushButton(self.groupbox_commands)
        self.btn_beep_lo.setObjectName(_fromUtf8("btn_beep_lo"))
        self.gridLayout.addWidget(self.btn_beep_lo, 2, 0, 1, 1)
        self.btn_beep_hi = QtGui.QPushButton(self.groupbox_commands)
        self.btn_beep_hi.setObjectName(_fromUtf8("btn_beep_hi"))
        self.gridLayout.addWidget(self.btn_beep_hi, 2, 1, 1, 1)
        self.btn_clean = QtGui.QPushButton(self.groupbox_commands)
        self.btn_clean.setObjectName(_fromUtf8("btn_clean"))
        self.gridLayout.addWidget(self.btn_clean, 3, 0, 1, 1)
        self.btn_spot = QtGui.QPushButton(self.groupbox_commands)
        self.btn_spot.setObjectName(_fromUtf8("btn_spot"))
        self.gridLayout.addWidget(self.btn_spot, 3, 1, 1, 1)
        self.btn_vacuum_on = QtGui.QPushButton(self.groupbox_commands)
        self.btn_vacuum_on.setObjectName(_fromUtf8("btn_vacuum_on"))
        self.gridLayout.addWidget(self.btn_vacuum_on, 4, 0, 1, 1)
        self.btn_vacuum_off = QtGui.QPushButton(self.groupbox_commands)
        self.btn_vacuum_off.setObjectName(_fromUtf8("btn_vacuum_off"))
        self.gridLayout.addWidget(self.btn_vacuum_off, 4, 1, 1, 1)
        self.btn_leds = QtGui.QPushButton(self.groupbox_commands)
        self.btn_leds.setObjectName(_fromUtf8("btn_leds"))
        self.gridLayout.addWidget(self.btn_leds, 5, 0, 1, 1)
        self.btn_sensors = QtGui.QPushButton(self.groupbox_commands)
        self.btn_sensors.setObjectName(_fromUtf8("btn_sensors"))
        self.gridLayout.addWidget(self.btn_sensors, 5, 1, 1, 1)
        self.layout_controls.addWidget(self.groupbox_commands)
        self.groupbox_control = QtGui.QGroupBox(self.centralWidget)
        self.groupbox_control.setObjectName(_fromUtf8("groupbox_control"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupbox_control)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.layout_arrows = QtGui.QGridLayout()
        self.layout_arrows.setObjectName(_fromUtf8("layout_arrows"))
        self.btn_arrow_left = QtGui.QPushButton(self.groupbox_control)
        self.btn_arrow_left.setObjectName(_fromUtf8("btn_arrow_left"))
        self.layout_arrows.addWidget(self.btn_arrow_left, 1, 0, 1, 1)
        self.btn_arrow_down = QtGui.QPushButton(self.groupbox_control)
        self.btn_arrow_down.setObjectName(_fromUtf8("btn_arrow_down"))
        self.layout_arrows.addWidget(self.btn_arrow_down, 2, 1, 1, 1)
        self.btn_arrow_right = QtGui.QPushButton(self.groupbox_control)
        self.btn_arrow_right.setObjectName(_fromUtf8("btn_arrow_right"))
        self.layout_arrows.addWidget(self.btn_arrow_right, 1, 2, 1, 1)
        self.btn_arrow_up = QtGui.QPushButton(self.groupbox_control)
        self.btn_arrow_up.setObjectName(_fromUtf8("btn_arrow_up"))
        self.layout_arrows.addWidget(self.btn_arrow_up, 0, 1, 1, 1)
        self.btn_stop = QtGui.QPushButton(self.groupbox_control)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.layout_arrows.addWidget(self.btn_stop, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.layout_arrows, 0, 0, 1, 1)
        self.text_cli = QtGui.QLineEdit(self.groupbox_control)
        self.text_cli.setObjectName(_fromUtf8("text_cli"))
        self.gridLayout_4.addWidget(self.text_cli, 1, 0, 1, 1)
        self.layout_speed_info = QtGui.QHBoxLayout()
        self.layout_speed_info.setObjectName(_fromUtf8("layout_speed_info"))
        self.speed_label = QtGui.QLabel(self.groupbox_control)
        self.speed_label.setObjectName(_fromUtf8("speed_label"))
        self.layout_speed_info.addWidget(self.speed_label)
        self.speed_value_label = QtGui.QLabel(self.groupbox_control)
        self.speed_value_label.setObjectName(_fromUtf8("speed_value_label"))
        self.layout_speed_info.addWidget(self.speed_value_label)
        self.gridLayout_4.addLayout(self.layout_speed_info, 5, 0, 1, 1)
        self.slider_speed = QtGui.QSlider(self.groupbox_control)
        self.slider_speed.setMaximum(500)
        self.slider_speed.setProperty(_fromUtf8("value"), 100)
        self.slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_speed.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_speed.setObjectName(_fromUtf8("slider_speed"))
        self.gridLayout_4.addWidget(self.slider_speed, 3, 0, 1, 1)
        self.layout_controls.addWidget(self.groupbox_control)
        self.verticalLayout.addLayout(self.layout_controls)
        self.log_text = QtGui.QTextEdit(self.centralWidget)
        self.log_text.setObjectName(_fromUtf8("log_text"))
        self.verticalLayout.addWidget(self.log_text)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 668, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.slider_speed, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.speed_value_label.setNum)
        QtCore.QObject.connect(self.text_cli, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.sendCommand)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_roomba_at.setText(QtGui.QApplication.translate("MainWindow", "Roomba at", None, QtGui.QApplication.UnicodeUTF8))
        self.text_roomba_ip.setText(QtGui.QApplication.translate("MainWindow", "192.168.0.11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_roomba_on.setText(QtGui.QApplication.translate("MainWindow", "on", None, QtGui.QApplication.UnicodeUTF8))
        self.text_roomba_port.setText(QtGui.QApplication.translate("MainWindow", "/dev/ttyUSB0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_commands.setTitle(QtGui.QApplication.translate("MainWindow", "Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset.setText(QtGui.QApplication.translate("MainWindow", "(R)eset", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_test.setText(QtGui.QApplication.translate("MainWindow", "(T)est", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_power_off.setText(QtGui.QApplication.translate("MainWindow", "(P)ower off", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_wake_up.setText(QtGui.QApplication.translate("MainWindow", "(W)ake up", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_beep_lo.setText(QtGui.QApplication.translate("MainWindow", "Beep (l)o", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_beep_hi.setText(QtGui.QApplication.translate("MainWindow", "Beep (h)i", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clean.setText(QtGui.QApplication.translate("MainWindow", "(C)lean", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_spot.setText(QtGui.QApplication.translate("MainWindow", "(S)pot", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_vacuum_on.setText(QtGui.QApplication.translate("MainWindow", "(V)acuum on", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_vacuum_off.setText(QtGui.QApplication.translate("MainWindow", "Vac(u)um off", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_leds.setText(QtGui.QApplication.translate("MainWindow", "(B)link LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sensors.setText(QtGui.QApplication.translate("MainWindow", "Sensors", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_control.setTitle(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arrow_left.setText(QtGui.QApplication.translate("MainWindow", "Left (←)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arrow_down.setText(QtGui.QApplication.translate("MainWindow", "Back (↓)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arrow_right.setText(QtGui.QApplication.translate("MainWindow", "Right (→)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arrow_up.setText(QtGui.QApplication.translate("MainWindow", "Forward (↑)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop (space)", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_label.setText(QtGui.QApplication.translate("MainWindow", "Speed (mm/s):", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_value_label.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))

